# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: image_generation.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'image_generation.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16image_generation.proto\x12\x0fimagegeneration\"=\n\x0cImageRequest\x12\x0e\n\x06prompt\x18\x01 \x01(\t\x12\x0c\n\x04size\x18\x02 \x01(\t\x12\x0f\n\x07\x61pi_key\x18\x03 \x01(\t\"\x1e\n\rImageResponse\x12\r\n\x05image\x18\x01 \x01(\t2h\n\x16ImageGenerationService\x12N\n\rGenerateImage\x12\x1d.imagegeneration.ImageRequest\x1a\x1e.imagegeneration.ImageResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'image_generation_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_IMAGEREQUEST']._serialized_start=43
  _globals['_IMAGEREQUEST']._serialized_end=104
  _globals['_IMAGERESPONSE']._serialized_start=106
  _globals['_IMAGERESPONSE']._serialized_end=136
  _globals['_IMAGEGENERATIONSERVICE']._serialized_start=138
  _globals['_IMAGEGENERATIONSERVICE']._serialized_end=242
# @@protoc_insertion_point(module_scope)
